/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.codingmechanic.framework.ScriptBase;
import org.testng.annotations.Test;

/**
 * Created by masihur on 3/26/17.
 */
public class TestCase extends ScriptBase{

    @Test
    public void test(){
        application.getPage().serchText("Masihur");
        application.getPage().clickSearch();
    }

    @Test
    public void test1(){
        application.getPage().serchText("Masihur");
        application.getPage().clickSearch();
    }
}
